name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16,20]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.0
      - run: pnpm i --frozen-lockfile
      - run: pnpm i -g .
      - run: fast-folder-size .
      - run: pnpm run lint
      - run: pnpm test
